global using Basket.API.Models;
global using ClassLib.CQRS;
global using Carter;
global using MediatR;
global using Mapster;
global using ClassLib.Behaviors;
global using FluentValidation;
global using ClassLib.Exceptions;
global using Marten;
