version: '3.4'

services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres
  
  cachedb:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
